#version 460
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 1, row_major, std140) uniform CameraUBO {
    mat4 invViewProj;
    vec3 camPos;
} uCam;

layout(set = 0, binding = 3, rgba8) uniform image2D rtImage;
layout(set = 0, binding = 4) uniform accelerationStructureEXT topLevelAS;

layout(location = 0) rayPayloadEXT vec3 payload;

struct ShadowPayload {
    uint visible;
};

void main()
{
    uvec2 launchID   = gl_LaunchIDEXT.xy;
    uvec2 launchSize = gl_LaunchSizeEXT.xy;
    vec2 ndc = (vec2(launchID) + 0.5) / vec2(launchSize) * 2.0 - 1.0;
    vec4 clip  = vec4(ndc, 0.0, 1.0);
    vec4 world = clip * uCam.invViewProj;
    world /= world.w;

    vec3 origin = uCam.camPos;
    vec3 dir    = normalize(world.xyz - origin);

    // Default payload (used if miss)
    payload = vec3(0.0);

    traceRayEXT(
        topLevelAS,
        gl_RayFlagsOpaqueEXT,
        0xFF,            // cullMask
        0,               // sbtRecordOffset
        1,               // sbtRecordStride
        0,               // missIndex
        origin,
        0.001,           // tmin
        dir,
        1e38,            // tmax
        0                // payload location
    );

    //store to image
    imageStore(rtImage, ivec2(launchID), vec4(payload, 1.0));
}
